import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Landing from '../component/landing/landing'
import AboutUs from '../component/aboutus/AboutUs'
import Cards from '../component/cards/Card'
import News from '../component/news/News'
import Services from '../component/services/Services'
import Testimonials from '../component/testimonials/Testimonials'
import Awards from '../component/awards/Award'
import Gallery from '../component/gallery/Gallery'

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from '../component/footer/Footer'
import Faqs from '../component/faqs/Faqs'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EverFastFright</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing/>
      <div className={styles.space_about}></div>
      <AboutUs/>
      <div className={styles.space}></div>
      {/* <Cards/>
      <div className={styles.space}></div>
      <News/>
      <div className={styles.space}></div>
      <Services/>
      <div className={styles.space}></div>
      <Testimonials/>
      <div className={styles.space}></div>
      <Awards/>
      <div className={styles.space}></div>
      <Gallery/>
      <div className={styles.space}></div>
      <Faqs/>
      <div className={styles.space}></div>
      <Footer/> */}
    </div>
  )
}
