import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Landing from './landing'
import Page2 from './page2'
import Page3 from './page3'
import Page4 from './page4'
import Page5 from './page5'
import Page6 from './page6'
import Page7 from './page7'
import Page8 from './page8'

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from '../component/footer/Footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EverFastFright</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing/>
      <Page2/>
      <Page3/>
      <Page4/>
      <Page5/>
      <Page6/>
      <Page7/>
      <Page8/>
      <Footer/>
    </div>
  )
}
